spring:
  profiles:
    active: dev # Selecciona el perfil por defecto
  mail:
    host: smtp.gmail.com
    port: 587
    username: y2kdsp@gmail.com
    password: kocu vbig qlhl tdzo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  packages-to-scan: com.sena.hidden_pass.infrastructure.entry_points
  paths-to-match: "/api/v1/hidden_pass/**"  # Ajusta según tu estructura de rutas